apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-bekk
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-bekk
    app.kubernetes.io/part-of: tkrw-pr712-0075-0073-app
  name: devfile-sample-bekk
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-bekk
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-bekk
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0073-tenant/tkrw-pr712-0075-0073-app/devfile-sample-bekk@sha256:bf228e9af9499bfb86c563140d691f735afc9712e4f592964f8e64874e6d2de1
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
